openapi: 3.0.0
info:
  title: Genomics Treatment API
  version: 1.0.0
paths:
  /ingest:
    post:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:data-ingestion-service/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /train:
    post:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:model-training-service/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /predict:
    post:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:treatment-prediction-service/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /patient:
    post:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:patient-management-service/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
  /update_dashboard:
    post:
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:123456789012:function:powerbi-integration-service/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy